### ISSUE TITLE
Implement s3 storage

### ISSUE THREAD

**Issue by mdanzinger** [rapid7/pdf-renderer#1]
Hi! I noticed there's an "upload to s3" task on the TODO list, I was wondering if I can go ahead and work on implementing that.

**Comment by vjiandani-r7** [comment]
Sorry. Not sure why I didn't get an email about this issue but yes, you are welcome to work on that.

**Comment by mdanzinger** [comment]
@vjiandani-r7 No worries at all. I noticed you have encryption for your local disk storage implementation. Is S3's Server-Side encryption adequate, or were you hoping to encrypt/decrypt client side?

**Comment by vjiandani-r7** [comment]
Server side encryption is okay. Client side can be a todo upon request imo.

I haven't decided whether I wanted to make the storage strategy locked in at start up via an environment variable or whether to make it part of the http request. I'm leaning towards the former though. Any thoughts?

**Comment by mdanzinger** [comment]
Sounds good! Since there are going to be multiple 'storages', the way I think I would personally approach it is to create a general `storage` interface, and inject the appropriate storage implementation at run time via cli flags or potentially environment variables. I don't think I would make it part of the http request personally, but I'll work with whatever you think is best!

**Comment by vjiandani-r7** [comment]
Perfect.

For your reference: https://github.com/rapid7/pdf-renderer/pull/2

**Comment by vjiandani-r7** [comment]
I separated the correlation and storage functionality and made noop the default storage option (don't store). You can also do "disk" which I figured would be useful for people who want to keep a backup of all pdfs generated and store them in an EBS or something.

Your path to adding support for S3 should be pretty clear now.

**Comment by mdanzinger** [comment]
Awesome! I'm out of town for a couple weeks, but I should be able to shoot you a PR when I return.

**Comment by vjiandani-r7** [comment]
@mdanzinger just wanted to check in with you and see if you still would like to do this.

**Comment by mdanzinger** [comment]
@vjiandani-r7 Hey, my apologies regarding the delay. I'm going to try and tackle this over the weekend.

**Comment by vjiandani-r7** [comment]
It's cool. Just trying to keep the gears turning.

**Comment by mdanzinger** [comment]
@vjiandani-r7 PR sent! https://github.com/rapid7/pdf-renderer/pull/6

**Comment by vjiandani-r7** [comment]
Completed.
